import pprint

import networkx as nx
import torch


def _tensor_data(tensor):
    return tensor.detach().cpu().tolist()


def _module_spec(module):
    name = module.__class__.__name__
    spec = {"type": name}
    if name == "LearnableParameter":
        spec["value"] = _tensor_data(module.value)
    elif name == "Constant":
        spec["value"] = _tensor_data(module.value)
    elif name == "Activation":
        spec["learnable"] = bool(module.learnable)
        if module.learnable:
            spec["raw_sharpness"] = float(module.raw_sharpness.detach().cpu())
            spec["raw_symmetry"] = float(module.raw_symmetry.detach().cpu())
            spec["raw_gate"] = float(module.raw_gate.detach().cpu())
        else:
            spec["sharpness"] = float(module.sharpness.detach().cpu())
            spec["symmetry"] = float(module.symmetry.detach().cpu())
            spec["gate"] = float(module.gate.detach().cpu())
    elif name == "Normalizer":
        spec["dimension"] = int(module.dimension)
        spec["affine"] = bool(module.affine)
    elif name == "Pooling":
        spec["dimension"] = int(module.dimension)
        spec["strategy"] = module.strategy
    elif name == "SoftMax":
        spec["dim"] = int(module.dim)
    elif name == "Concat":
        spec["dimension"] = int(module.dimension)
    elif name == "Split":
        spec["dimension"] = int(module.dimension)
        spec["fraction"] = float(module.fraction)
    elif name == "Shift":
        spec["amount"] = int(module.amount)
        spec["dim"] = int(module.dim)
    elif name == "Noise":
        spec["noise_type"] = module.noise_type
        spec["scale"] = float(module.scale)
        spec["per_tensor"] = bool(module.per_tensor)
    elif name == "EMA":
        spec["raw_alpha"] = float(module.raw_alpha.detach().cpu())
    elif name == "EinsteinAggregator":
        spec["seed"] = int(getattr(module, "_seed", 0))
        spec["notation"] = module.notation
        spec["T"] = float(module.T) if module.T is not None else None
    return spec


def export_architecture_python(arch, class_name="ExportedEmernetModel"):
    if not arch.isValid(verbose=False):
        raise ValueError("Architecture must be valid before Python export")
    topo_order = list(nx.topological_sort(arch))
    specs = {
        "nodes": {str(node): _module_spec(arch.nodes[node]["module"]) for node in topo_order},
        "edges": [[str(u), str(v)] for u, v in arch.edges()],
        "topo_order": [str(node) for node in topo_order],
        "predecessors": {str(node): [str(p) for p in arch.predecessors(node)] for node in topo_order},
        "output_node": str(arch.get_Output_id()),
    }
    specs_literal = pprint.pformat(specs, width=120, sort_dicts=False)
    return f'''"""
Standalone PyTorch export generated by Emernet.

Import usage:
    from exported_architecture import {class_name}
    model = {class_name}()
    y = model(x)  # x is expected as a 3D tensor: batch, positions, features
"""

import math
import random
from itertools import permutations

import torch
import torch.nn as nn
import torch.nn.functional as F


ARCH_SPEC = {specs_literal}


class SourceTensor(nn.Module):
    def __init__(self, value, trainable=False):
        super().__init__()
        tensor = torch.tensor(value, dtype=torch.float32)
        if trainable:
            self.value = nn.Parameter(tensor)
        else:
            self.register_buffer("value", tensor)

    def forward(self, x=None):
        return [self.value]


class ActivationNode(nn.Module):
    def __init__(self, spec):
        super().__init__()
        self.learnable = bool(spec.get("learnable", False))
        if self.learnable:
            self.raw_sharpness = nn.Parameter(torch.tensor(float(spec.get("raw_sharpness", 0.0))))
            self.raw_symmetry = nn.Parameter(torch.tensor(float(spec.get("raw_symmetry", 0.0))))
            self.raw_gate = nn.Parameter(torch.tensor(float(spec.get("raw_gate", 0.0))))
        else:
            self.register_buffer("sharpness", torch.tensor(float(spec.get("sharpness", 0.5))))
            self.register_buffer("symmetry", torch.tensor(float(spec.get("symmetry", 0.5))))
            self.register_buffer("gate", torch.tensor(float(spec.get("gate", 0.5))))

    def forward(self, xs):
        if self.learnable:
            sharpness = torch.sigmoid(self.raw_sharpness)
            symmetry = torch.sigmoid(self.raw_symmetry)
            gate = torch.sigmoid(self.raw_gate)
        else:
            sharpness, symmetry, gate = self.sharpness, self.symmetry, self.gate
        out = []
        for x in xs:
            base = (1 - sharpness) * torch.tanh(x) + sharpness * torch.relu(x)
            base = (1 - symmetry) * torch.relu(base) + symmetry * base
            out.append(gate * x * torch.sigmoid(x) + (1 - gate) * base)
        return out


class AddNode(nn.Module):
    def __init__(self, multiply=False):
        super().__init__()
        self.multiply = multiply
        self.p_projections = None
        self.f_projections = None

    def forward(self, xs):
        if self.p_projections is None:
            self.p_projections = nn.ModuleList()
            self.f_projections = nn.ModuleList()
            max_f = max(t.shape[-1] for t in xs)
            max_p = max(t.shape[-2] for t in xs)
            for t in xs:
                self.f_projections.append(nn.Linear(t.shape[-1], max_f) if t.shape[-1] != max_f else nn.Identity())
                self.p_projections.append(nn.Linear(t.shape[-2], max_p) if t.shape[-2] != max_p else nn.Identity())
            self.to(xs[0].device)
        result = None
        for t, fp, pp in zip(xs, self.f_projections, self.p_projections):
            adapted = pp(fp(t).transpose(1, 2)).transpose(1, 2)
            result = adapted if result is None else (result * adapted if self.multiply else result + adapted)
        return [result]


class MatMulNode(nn.Module):
    def __init__(self):
        super().__init__()
        self.projections = None

    def forward(self, xs):
        y = xs[0]
        if self.projections is None:
            self.projections = nn.ModuleList()
            running = y.shape[-1]
            for t in xs[1:]:
                self.projections.append(nn.Linear(running, t.shape[-2]) if running != t.shape[-2] else nn.Identity())
                running = t.shape[-1]
            self.to(xs[0].device)
        for t, proj in zip(xs[1:], self.projections):
            y = torch.matmul(proj(y), t)
        return [y]


class NormalizerNode(nn.Module):
    def __init__(self, spec):
        super().__init__()
        self.dimension = int(spec.get("dimension", 0))
        self.affine = bool(spec.get("affine", True))
        self.norm_layers = None

    def forward(self, xs):
        if self.norm_layers is None:
            self.norm_layers = nn.ModuleList()
            for t in xs:
                if self.dimension == 0:
                    self.norm_layers.append(nn.LayerNorm(t.shape[-1], elementwise_affine=self.affine))
                elif self.dimension == 1:
                    self.norm_layers.append(nn.BatchNorm1d(t.shape[-1], affine=self.affine))
                else:
                    self.norm_layers.append(nn.InstanceNorm1d(t.shape[-1], affine=self.affine))
            self.to(xs[0].device)
        out = []
        for t, layer in zip(xs, self.norm_layers):
            if self.dimension == 0:
                out.append(layer(t))
            else:
                y = t.transpose(1, 2)
                if (self.dimension == 1 and y.shape[0] > 1) or (self.dimension == 2 and y.shape[-1] > 1):
                    y = layer(y)
                out.append(y.transpose(1, 2))
        return out


class PoolingNode(nn.Module):
    def __init__(self, spec):
        super().__init__()
        self.dimension = int(spec.get("dimension", 2))
        self.strategy = spec.get("strategy", "mean")

    def forward(self, xs):
        if self.strategy == "mean":
            return [torch.mean(t, dim=self.dimension, keepdim=True) for t in xs]
        if self.strategy == "min":
            return [torch.min(t, dim=self.dimension, keepdim=True).values for t in xs]
        if self.strategy == "max":
            return [torch.max(t, dim=self.dimension, keepdim=True).values for t in xs]
        return [torch.median(t, dim=self.dimension, keepdim=True).values for t in xs]


class ConcatNode(nn.Module):
    def __init__(self, spec):
        super().__init__()
        self.dimension = int(spec.get("dimension", 2))
        self.projections = None

    def forward(self, xs):
        if self.projections is None:
            match_dim = 2 if self.dimension == 1 else 1
            max_size = max(t.shape[match_dim] for t in xs)
            self.projections = nn.ModuleList([
                nn.Linear(t.shape[match_dim], max_size) if t.shape[match_dim] != max_size else nn.Identity()
                for t in xs
            ])
            self.to(xs[0].device)
        adapted = []
        for t, proj in zip(xs, self.projections):
            adapted.append(proj(t) if self.dimension == 1 else proj(t.transpose(1, 2)).transpose(1, 2))
        return [torch.cat(adapted, dim=self.dimension)]


class SplitNode(nn.Module):
    def __init__(self, spec):
        super().__init__()
        self.dimension = int(spec.get("dimension", 2))
        self.fraction = float(spec.get("fraction", 0.5))

    def forward(self, xs):
        out = []
        for t in xs:
            dim_size = t.shape[self.dimension]
            if dim_size <= 1:
                out.extend([t, t])
            else:
                split_idx = max(1, min(dim_size - 1, int(dim_size * self.fraction)))
                a, b = torch.split(t, [split_idx, dim_size - split_idx], dim=self.dimension)
                out.extend([a.clone(), b.clone()])
        return out


class EinsteinAggregatorNode(nn.Module):
    _cache = {{}}
    _order_cache = {{}}

    def __init__(self, spec):
        super().__init__()
        self._seed = int(spec.get("seed", 0))
        self.notation = spec.get("notation")
        self.T = spec.get("T")

    def init_notation(self, n_inputs):
        if self.notation is not None and self.T is not None:
            return
        rng = random.Random(self._seed)
        max_unique = 6
        inputs = ["abc"]
        used = {{"a", "b", "c"}}
        for _ in range(1, n_inputs):
            symbols = ["a"]
            for _ in range(2):
                if len(used) < max_unique and rng.random() < 0.3:
                    new_symbol = chr(ord(max(used)) + 1)
                    symbols.append(new_symbol)
                    used.add(new_symbol)
                else:
                    available = [s for s in used if s not in symbols and s != "a"]
                    symbols.append(rng.choice(available or list(used - {{"a"}})))
            inputs.append("".join(symbols))
        output = "a"
        available = list(used - {{"a"}})
        rng.shuffle(available)
        for _ in range(2):
            if rng.random() > 0.1 and available:
                output += available.pop()
        self.notation = ",".join(inputs) + "->" + output
        self.T = max(1e-6, 1.0 + rng.gauss(0, 1.33))

    def forward(self, xs):
        self.init_notation(len(xs))
        try:
            input_side, output_side = self.notation.split("->")
            notes = input_side.split(",")
            symbol_to_max = {{}}
            for t, note in zip(xs, notes):
                for j, symbol in enumerate(note):
                    symbol_to_max[symbol] = max(symbol_to_max.get(symbol, 0), t.shape[j])
            padded = []
            for t, note in zip(xs, notes):
                pads = []
                for j in range(len(note) - 1, -1, -1):
                    pads.extend([0, symbol_to_max[note[j]] - t.shape[j]])
                padded.append(F.pad(t, tuple(pads)) if any(pads) else t)
            result = torch.einsum(self.notation, *padded)
            if result.dim() == 1:
                result = result.view(result.shape[0], 1, 1)
            elif result.dim() == 2:
                result = result.view(result.shape[0], result.shape[1], 1)
            elif result.dim() > 3:
                result = result.view(result.shape[0], result.shape[1], -1)
            return [result]
        except Exception:
            reduced = [t.mean(dim=tuple(range(1, t.dim())), keepdim=True) for t in xs]
            return [sum(reduced) / len(reduced)]


class EMANode(nn.Module):
    def __init__(self, spec):
        super().__init__()
        self.raw_alpha = nn.Parameter(torch.tensor(float(spec.get("raw_alpha", 0.0))))

    def forward(self, xs):
        alpha = torch.sigmoid(self.raw_alpha)
        out = []
        for x in xs:
            h = torch.zeros(x.shape[0], x.shape[-1], device=x.device)
            steps = []
            for idx in range(x.shape[1]):
                h = alpha * h + (1 - alpha) * x[:, idx, :]
                steps.append(h)
            out.append(torch.stack(steps, dim=1))
        return out


def build_node(spec):
    t = spec["type"]
    if t == "Input":
        return None
    if t == "LearnableParameter":
        return SourceTensor(spec["value"], trainable=True)
    if t == "Constant":
        return SourceTensor(spec["value"], trainable=False)
    if t == "Activation":
        return ActivationNode(spec)
    if t == "Add":
        return AddNode(False)
    if t == "Mult":
        return AddNode(True)
    if t == "MatMul":
        return MatMulNode()
    if t == "Accumulator":
        return nn.ModuleList()
    if t == "Normalizer":
        return NormalizerNode(spec)
    if t == "Pooling":
        return PoolingNode(spec)
    if t == "SoftMax":
        return nn.Softmax(dim=int(spec.get("dim", 2)))
    if t == "Concat":
        return ConcatNode(spec)
    if t == "Split":
        return SplitNode(spec)
    if t == "Shift":
        return None
    if t == "Transpose":
        return None
    if t == "EMA":
        return EMANode(spec)
    if t == "EinsteinAggregator":
        return EinsteinAggregatorNode(spec)
    if t == "Noise":
        return None
    raise ValueError(f"Unsupported node type: {{t}}")


class {class_name}(nn.Module):
    def __init__(self):
        super().__init__()
        self.spec = ARCH_SPEC
        self.nodes = nn.ModuleDict()
        for node_id, spec in self.spec["nodes"].items():
            node = build_node(spec)
            if isinstance(node, nn.Module):
                self.nodes[node_id] = node

    def _source_forward(self, node_id, x):
        spec = self.spec["nodes"][node_id]
        if spec["type"] == "Input":
            return [x]
        return self.nodes[node_id]()

    @staticmethod
    def pick_output(raw_outputs):
        max_batch = max(t.shape[0] for t in raw_outputs)
        return next(t for t in raw_outputs if t.shape[0] == max_batch)

    def forward(self, x):
        outputs = {{}}
        for node_id in self.spec["topo_order"]:
            spec = self.spec["nodes"][node_id]
            node_type = spec["type"]
            if node_type in ("Input", "LearnableParameter", "Constant"):
                outputs[node_id] = self._source_forward(node_id, x)
                if node_type != "Input":
                    outputs[node_id] = [
                        t.expand(x.shape[0], -1, -1) if t.dim() >= 2 and t.shape[0] == 1 and x.shape[0] > 1 else t
                        for t in outputs[node_id]
                    ]
                continue
            inputs = []
            for pred in self.spec["predecessors"][node_id]:
                inputs.extend(outputs[pred])
            if node_type == "Accumulator":
                outputs[node_id] = [torch.cumsum(t, dim=1) for t in inputs]
            elif node_type == "SoftMax":
                outputs[node_id] = [self.nodes[node_id](t) for t in inputs]
            elif node_type == "Shift":
                outputs[node_id] = [torch.roll(t, shifts=int(spec.get("amount", 0)), dims=int(spec.get("dim", 1))) for t in inputs]
            elif node_type == "Transpose":
                outputs[node_id] = [t.transpose(1, 2) for t in inputs]
            elif node_type == "Noise":
                if self.training:
                    scale = float(spec.get("scale", 0.1))
                    kind = spec.get("noise_type", "gaussian")
                    noisy = []
                    for t in inputs:
                        if kind == "uniform":
                            n = (torch.rand_like(t) * 2 - 1) * scale
                        elif kind == "bernoulli":
                            n = (torch.rand_like(t) < scale).float()
                        else:
                            n = torch.randn_like(t) * scale
                        noisy.append(t + n)
                    outputs[node_id] = noisy
                else:
                    outputs[node_id] = inputs
            else:
                outputs[node_id] = self.nodes[node_id](inputs)
        return self.pick_output(outputs[self.spec["output_node"]])


__all__ = ["{class_name}", "ARCH_SPEC"]
'''
